apiVersion: v1
kind: Secret
metadata:
  name: user-toml
type: Opaque
data:
  # Needs to be base64-encoded.
  user.toml: W3NlcnZlcl0KYmluZCA9ICIwLjAuMC4wIgoKW2NsaWVudF0KYmluZCA9ICIwLjAuMC4wIgo=
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
customVersion: v1beta2
metadata:
  ## Name of the Kubernetes resource.
  name: consul-latest
spec:
  v1beta2:
    ## Name of the Habitat service package exported as a Docker image.
    # image: core/consul:1.2.2-20180731175223
    image: qbrd/consul:latest
    ## Number of desired instances.
    count: 3
    ## An object containing parameters that affects how the Habitat service
    ## is executed.
    service:
      ## Name of the Habitat service.
      name: consul
      # set us up to run in leader/follower topology: https://www.habitat.sh/docs/using-habitat/#topologies
      topology: leader
      # Name of secret to use
      configSecretName: user-toml
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  selector:
    habitat-name: example-configured-habitat
  # type: NodePort
  type: LoadBalancer
  ports:
  # This endpoint displays the message from the secret
  - name: consul
    # nodePort: 8500
    # This is the custom port set in the user.toml
    port: 8500
    protocol: TCP
  # This endpoint exposes the Habitat supervisor API
  - name: consul-dns-tcp
    # nodePort : 8600
    port: 8600
    protocol: TCP
  # - name: consul-dns-udp
  #   # nodePort : 8600
  #   port: 8600
  #   protocol: UDP
